### ISSUE TITLE
Analysis Error: Attribute PROFANITY does not support request languages: it

### ISSUE THREAD

**Issue by rsese** [atom/biohazard-alert#11] opened 2019-04-09 05:15 UTC
Error from the alert:

```
400 - {"error":{"code":400,"message":"Attribute PROFANITY does not support request languages: it","status":"INVALID_ARGUMENT"}}
```

Comment seems to be deleted so can't link to it 📎

**Comment by lee-dohm** [comment] 2019-04-09 19:18
This was caused by a very short English comment that had misspellings in it, causing the analysis engine to believe that it was written in Italian. Perspective doesn't have some of the alternate models we request for Italian, so it returned this error.

This is the expected behavior, as I suspect it would be useful for us to be notified when people post in languages other than English, so we can manually check for toxicity. But, that's assuming that the language detection is very nearly flawless. If it is less accurate than that, we may need to rethink this use case.

I'm going to close this for now, since there isn't anything specific to be done. But please keep opening (or reopen if they reoccur) Analysis Error issues so that we can continue to root cause the problems.

**Closed by lee-dohm** 2019-04-09 19:18 UTC
